name: Terraform Governance

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_organization: ${{ github.repository_owner }}
      GITHUB_APP_ID: ${{ secrets.TF_GITHUB_APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_GITHUB_APP_INSTALLATION_ID }}
      GITHUB_APP_PEM_FILE: ${{ secrets.TF_GITHUB_APP_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::762233769464:role/github-actions-terraform
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -lock-timeout=15s -out=tfplan

      # - name: Wait for approval
      #   if: github.ref == 'refs/heads/main'
      #   uses: trstringer/manual-approval@74d99dff7380e3e4b122d4ededcbca2b6ce59367 # v1.12.0
      #   timeout-minutes: 20
      #   with:
      #     secret: ${{ github.token }}
      #     approvers: gnersisyann
      #     minimum-approvals: 1
      #     exclude-workflow-initiator-as-approver: false
      #     issue-title: "Terraform apply approval (${{ github.ref_name }})"
      #     issue-body: |
      #       Please approve Terraform apply for release **${{ github.ref_name }}**.

      #       Repo: ${{ github.repository }}
      #       Commit: ${{ github.sha }}
      #       Actor: ${{ github.actor }}
      #       Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -lock-timeout=10m tfplan
